GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhNvbSIsImlhdCI6MTY1NjQzMzA4MSwiZXhwIjoxNjU2NTE5NDgxfQ.fekKFwSsCYNjT7gXtiabfUsAR8R2lQjpdmvqp47AsjI